#!/usr/bin/with-contenv bash
# shellcheck shell=bash

echo "\
    cargo \
    ffmpeg \
    gcc \
    git \
    libffi-dev \
    libmediainfo \
    musl-dev \
    openssl-dev \
    py3-cffi \
    py3-pip \
    python3-dev" >> /mod-repo-packages-to-install.list


echo "-r https://raw.githubusercontent.com/mdhiggins/sickbeard_mp4_automator/master/setup/requirements.txt" >> /mod-pip-packages-to-install.list
