#!/usr/bin/with-contenv bash

if [ ! -f /usr/bin/git ]; then
  echo '------------------------------------------------------------------------'
  echo '| Mod by Roxedus'
  echo '| Running installation of required modules for sickbeard_mp4_automator'
  echo '------------------------------------------------------------------------'
  apk add --no-cache \
    py3-pip \
    git \
    gcc \
    musl-dev \
    python3-dev \
    libffi-dev \
    openssl-dev \
    ffmpeg
  pip3 install --upgrade pip setuptools wheel
  pip3 install --no-cache-dir -U \
    requests \
    requests[security] \
    requests-cache \
    babelfish \
    tmdbsimple \
    mutagen \
    guessit \
    subliminal \
    python-dateutil \
    stevedore \
    pymediainfo \
    qtfaststart
fi
