#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [ ! -f /pip_deps ]; then
  echo '------------------------------------------------------------------------'
  echo '| Mod by Roxedus'
  echo '| Running installation of required modules for sickbeard_mp4_automator'
  echo '------------------------------------------------------------------------'
  apk add --no-cache \
    cargo \
    ffmpeg \
    gcc \
    git \
    libffi-dev \
    libmediainfo \
    musl-dev \
    openssl-dev \
    py3-cffi \
    py3-pip \
    python3-dev
  pip3 install --no-cache-dir --upgrade pip setuptools wheel
  pip3 install --no-cache-dir -U -r https://raw.githubusercontent.com/mdhiggins/sickbeard_mp4_automator/master/setup/requirements.txt --find-links https://wheel-index.linuxserver.io/alpine-3.16/
  touch /pip_deps
fi
