#!/usr/bin/with-contenv bash

if [ ! -f /usr/bin/git ]; then
  echo '------------------------------------------------------------------------'
  echo '| Mod by Roxedus'
  echo '| Running installation of required modules for sickbeard_mp4_automator'
  echo '------------------------------------------------------------------------'
  apk add --no-cache \
    cargo \
    ffmpeg \
    gcc \
    git \
    libffi-dev \
    libmediainfo \
    musl-dev \
    openssl-dev \
    py3-cffi \
    py3-pip \
    python3-dev
  pip3 install --upgrade pip setuptools wheel
  pip3 install --no-cache-dir -U -r https://raw.githubusercontent.com/mdhiggins/sickbeard_mp4_automator/master/setup/requirements.txt
fi
