#!/usr/bin/with-contenv bash

echo '-------------------------'
echo '| Mod by Roxedus'
echo '| Getting latest scripts'
echo '-------------------------'

git config --global --add safe.directory /SickBeard

# Clone sickbeard_mp4_automator repo
if [[ ! -d /SickBeard/.git ]]; then
  echo '-----------------------'
  echo '| Downloading Scripts'
  echo '-----------------------'
  git clone https://github.com/mdhiggins/sickbeard_mp4_automator /SickBeard
elif [[ -d /SickBeard/.git ]]; then
  echo '-----------------------'
  echo '|  Updating Scripts'
  echo '-----------------------'
  cd /SickBeard || return
  git reset --hard origin/master
  git pull --rebase
fi

if [ -f /SickBeard/autoProcess.ini ]; then
  echo '--------------------------------'
  echo '| Moving files to new locations'
  echo '| NEW FORMAT. PLEASE CONSULT THE WIKI ON THE NEW FORMAT'
  echo '---------------------------------'
  mkdir /SickBeard/config
  mv /SickBeard/autoProcess.ini /SickBeard/config/autoProcess.ini
  find . -name /SickBeard/\*.pyc -delete
fi

# Make files. (needed if you want to mount the logs in IE. logarr)
touch /SickBeard/sma.log

# Permissions
chmod a+rwx -R /SickBeard

# Set Permissions
chown -R abc:abc \
  /SickBeard
