#!/usr/bin/with-contenv bash

if [ ! -d /usr/lib/python3.8/site-packages/requests ]; then
  echo '------------------------------------------------------------------------'
  echo '| Mod by Roxedus'
  echo '| Running installation of required modules for discord_f2b'
  echo '------------------------------------------------------------------------'
  pip3 install --no-cache-dir -U \
    requests \
    argparse \
    geoip2
fi

if [ ! -f /config/fail2ban/Fail2Ban.py ]; then
  cp /tmp/Fail2Ban.py /config/fail2ban/
fi

test=$(python3 /config/fail2ban/Fail2Ban.py -a test)
if [[ ${test} = 404 ]]; then
  echo 'Notifier might not work'
elif [[ ${test} = 204 ]]; then
  echo 'Notifier works'
fi