#!/usr/bin/with-contenv bash

if [ ! -d /usr/lib/python3.8/site-packages/geoip2 ]; then
  echo '------------------------------------------------------------------------'
  echo '| Mod by Roxedus'
  echo '| Running installation of required modules for discord_f2b'
  echo '------------------------------------------------------------------------'
  pip3 install --no-cache-dir -U \
    geoip2
    pytz
fi

if [ ! -f /config/fail2ban/Fail2Ban.py ]; then
  cp /AwesomeFolder/Fail2Ban.py /config/fail2ban/
  chmod +x /config/fail2ban/Fail2Ban.py
fi

if [ ! -f /config/fail2ban/action.d/discordEmbed.conf ]; then
  cp /AwesomeFolder/discordEmbed.conf /config/fail2ban/action.d
fi

# test=$(python3 /config/fail2ban/Fail2Ban.py -a test)
# if [[ ${test} = 404 ]]; then
#   echo 'Notifier might not work'
# elif [[ ${test} = 204 ]]; then
#   echo 'Notifier works'
# fi