#!/usr/bin/with-contenv bash

echo '-------------------------'
echo '| Mod by Roxedus        |'
echo '| Getting atest scripts |'
echo '-------------------------'

# Clone sickbeard_mp4_automator repo
if [[ ! -d /SickBeard/.git ]]; then
  echo '-----------------------'
  echo '| Downloading Scripts  |'
  echo '-----------------------'
  git clone https://github.com/mdhiggins/sickbeard_mp4_automator /SickBeard
elif [[ -d /SickBeard/.git ]]; then
  echo '-----------------------'
  echo '|  Updating Scripts    |'
  echo '-----------------------'
  cd /SickBeard || return
  git reset --hard origin/master
  git pull --rebase
fi

# Make files. (needed if you want to mount the logs in IE. logarr)
touch /SickBeard/info.log

# Permissions
chmod a+rwx -R /SickBeard

# Set Permissions
chown -R abc:abc \
	/SickBeard