#!/usr/bin/with-contenv bash

if [ ! -f /usr/bin/pip ]; then
  echo '------------------------------------------------------------------------'
  echo '| Mod by Roxedus'
  echo '| Running installation of required modules for sickbeard_mp4_automator'
  echo '------------------------------------------------------------------------'
  apk add --no-cache \
    py2-pip \
    git
  pip install --no-cache-dir -U \
    requests-cache \
    babelfish \
    'guessit<2' \
    'subliminal<2' \
    stevedore==1.19.1 \
    qtfaststart
fi