#!/usr/bin/with-contenv bash

if [ ! -f /usr/bin/pip ]; then
  echo '------------------------------------------------------------------------'
  echo '| Mod by Roxedus'
  echo '| Running installation of required modules for sickbeard_mp4_automator'
  echo '------------------------------------------------------------------------'
  sed -i -- 's/#deb-src/deb-src/g' /etc/apt/sources.list && sed -i -- 's/# deb-src/deb-src/g' /etc/apt/sources.list
  apt-get update
  apt-get install -y \
    python3 \
    ffmpeg \
    git \
    python3-pip
  pip3 install --no-cache-dir -U \
    requests \
    requests[security] \
    requests-cache \
    babelfish \
    tmdbsimple \
    mutagen \
    guessit \
    subliminal \
    python-dateutil \
    stevedore \
    qtfaststart
  rm -rf \
    /tmp/* \
    /var/lib/apt/lists/* \
    /var/tmp/*
fi