name: Build Docker-mod for discord_f2b

on:
  push:
    paths:
      - "init-run-custom-before-package/**"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TOKEN: ${{ secrets.docker_token }}
      DOCKER_REPO: roxedus/lsio-docker-mods
      APP: init-run-custom-before-package
      DIR: init-run-custom-before-package

    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: |
          cd ${DIR}
          docker build . --file Dockerfile --tag ${DOCKER_REPO}:${APP}-$(date --utc +%Y-%m-%d_%H.%M) --tag ${DOCKER_REPO}:${APP}-latest

      - name: Login to registry
        run: echo $TOKEN | docker login -u roxedus --password-stdin

      - name: Pushes the Docker mod
        run: docker push ${DOCKER_REPO}
