name: Build Docker-mod for init-run-custom-before-package

on:
  push:
    paths:
      - "init-run-custom-before-package/**"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TOKEN: ${{ secrets.docker_token }}
      DOCKER_REPO: roxedus/lsio-docker-mods
      APP: init-run-custom-before-package
      DIR: init-run-custom-before-package

    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: |
          cd "${DIR}"
          docker build . --file Dockerfile \
          --tag ${DOCKER_REPO}:${APP}-$(date --utc +%Y-%m-%d_%H.%M) --tag ${DOCKER_REPO}:${APP}-latest \
          --tag ghcr.io/${DOCKER_REPO}:${APP}-$(date --utc +%Y-%m-%d_%H.%M) --tag ghcr.io/${DOCKER_REPO}:${APP}-latest

      - name: Login and push to registry
        run: |
          echo $TOKEN | docker login -u roxedus --password-stdin
          docker push -a ${DOCKER_REPO}

      - name: Login and push to github registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u roxedus --password-stdin
          docker push -a ghcr.io/${DOCKER_REPO}