name: Build Docker-mod for lsio-ubuntu

on:
  push:
    paths:
      - "sickbeard automator/lsio-ubuntu/**"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TOKEN: ${{ secrets.docker_token }}
      DOCKER_REPO: roxedus/lsio-docker-mods
      APP: mp4-lsio-ubuntu
      DIR: sickbeard automator/lsio-ubuntu

    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: |
          cd ${DIR}
          docker build . --file Dockerfile \
          --tag ${DOCKER_REPO}:${APP}-$(date --utc +%Y-%m-%d_%H.%M) --tag ${DOCKER_REPO}:${APP}-latest \
          --tag ghcr.io/${DOCKER_REPO^}:${APP}-$(date --utc +%Y-%m-%d_%H.%M) --tag ghcr.io/${DOCKER_REPO^}:${APP}-latest

      - name: Login and push to registry
        run: |
          echo $TOKEN | docker login -u roxedus --password-stdin
          docker push -a ${DOCKER_REPO}

      - name: Login and push to github registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u roxedus --password-stdin
          docker push -a ghcr.io/${DOCKER_REPO^}
