name: Build Docker-mod for lsio-ubuntu

on:
  push:
    paths:
      - "sickbeard automator/lsio-ubuntu/**"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TOKEN: ${{ secrets.docker_token }}
      DOCKER_REPO: roxedus/lsio-docker-mods
      APP: mp4-lsio-ubuntu

    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: |
          cd "sickbeard automator/lsio-ubuntu"
          docker build . --file Dockerfile --tag ${DOCKER_REPO}:${APP}-$(date --utc +%Y-%m-%d_%H.%M) --tag ${DOCKER_REPO}:${APP}-latest

      - name: Login to registry
        run: echo $TOKEN | docker login -u roxedus --password-stdin

      - name: Pushes the Docker mod
        run: docker push -a ${DOCKER_REPO}
